[package]
name = "sump_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]

defmt-rtt = "0.4"
panic-probe = { version = "0.3", features = ["print-defmt"] }
cortex-m = { version = "0.7.6", features = ["inline-asm"] }
cortex-m-rt = "0.7.0"

[dependencies.embassy-executor]
version = "0.7.0"
features = ["task-arena-size-98304", "arch-cortex-m", "executor-thread",
	    "executor-interrupt", "defmt"]

[dependencies.embassy-rp]
version = "0.3.0"
features = ["defmt", "unstable-pac", "time-driver", "critical-section-impl",
	    "rp2040"]

[profile.release]
debug = 2
lto = true
opt-level = 'z'

[profile.dev]
debug = 2
lto = true
opt-level = "z"
